{{- if .Values.ingress.enabled -}}
        {{- $fullName := include "project.fullname" . -}}
        {{- $serviceName := include "project.fullname" . -}}
        {{- $servicePort := .Values.service.name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "project.name" . }}
    helm.sh/chart: {{ include "project.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
        {{- with .Values.ingress.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
        {{- end }}
spec:
        {{- if .Values.ingress.rules }}
  rules:
          {{- range $key, $val := .Values.ingress.rules }}
    - host: {{ $val.host | quote }}
            {{- if $val.http }}
      http:
              {{- if $val.http.paths }}
        paths:
                {{- range $key_, $val_ := $val.http.paths }}
          - path: {{ $val_.path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.ingress.https -}}
  tls:
          {{- range .Values.ingress.tls }}
    - hosts:
              {{- range .hosts }}
        - {{ . | quote }}
            {{- end }}
      secretName: {{ .secretName }}
          {{- end }}
        {{- end }}
        {{- end }}
