export const SI = 'Social Invest'
export const SE = 'Social Entrepreneurship Grant'
export const SP = 'Social Projects'
export const IG = 'Impulse Grant'
export const SG = 'Start Grant'
export const PG = 'Pilot Grant'
