## This is a YAML-formatted file. 

replicaCount: 1

image:
  repository: gitlab.almanit.kz:4567/portal-fsr/fsr-front-ui
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: gitlab-docker-registry

gitlab:
  enabled: true
  prometheus:
    enable: false
  labels:
    application: "CI_ENVIRONMENT_SLUG"
    release: "CI_ENVIRONMENT_SLUG"
  annotations:
    env: "env"
    app: "app"

env: []
#  CUBA_APP_URL: http://89.219.14.148:31753/app/rest/


## This variables is taken from secret
## Value is secret name where variable value can be found
## Key in secret equals lowercased variable name with "_" replaced by "-"
## The secret should be created manually
#envSecret:
#  SECRET_KEY_BASE: slurm3-xpaste
#  DB_USER: slurm3-xpaste
#  DB_PASSWORD: slurm3-xpaste

nameOverride: ""
fullnameOverride: ""

service:
  enable: true
  name: http
  targetPort: 80
  protocol: TCP
  port: 80
  nodePort:
    enable: false
    port: 31756

### Usage Probes
## support 2 types, probe by 'exec' and 'http'.
## uncomment what do you need. If probe types is not used set '[]'
#    exec: []
#      command:
#        - /bin/sh
#        - -c
#        - /var/www/html/project-app/check.sh
#    httpGet: []
#      path: /health
#      port: 80
#      scheme: HTTP
#      hashttpauth: false
#      value: Basic Yw==
healthcheck:
  readinessProbe:
    enable: false
    exec: []
    httpGet:
      path: /health
      port: 80
      scheme: HTTP
      hashttpauth: false
      value: Basic Yw==
    initialDelaySeconds: 10
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  livenessProbe:
    enable: false
    exec: []
    httpGet:
      path: /health
      port: 80
      scheme: HTTP
      hashttpauth: false
      value: Basic Yw==
    initialDelaySeconds: 15
    failureThreshold: 3
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 20

ingress:
  enabled: true
  https: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    certmanager.k8s.io/cluster-issuer: letsencrypt-dev
  tls:
    #     Secrets must be manually created in the namespace.
    - secretName: letsencrypt-dev
      hosts:
        - sdf.almanit.kz
        - sdftest.almanit.kz
  rules:
    sdf:
      host: sdftest.almanit.kz
      http:
        paths:
          - path: /((.*))

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

# metrics-server add-on required
hpa:
  enabled: false
  maxReplicas: 2
  # average total CPU usage per pod (1-100)
  cpu: 90
  # average memory usage per pod (100Mi-1Gi)
  #memory: 96Mi
  # average http requests per second per pod (k8s-prometheus-adapter)
  #requests:


persistence:
  enabled: false
persistent: []
#  storage:
#    storageClassName: "local"
#    capacity:
#      storage: 1Gi
#    accessMode: ReadWriteMany
#    hostPath:
#      path: ""
#    mountPath:
#      path: ""
#    exist: false
nfs: []
#  permanent:
#    server: 192.168.1.11 # Please change this to your NFS server
#    serverPath:
#      path: /var/www/nfsshare/sandbox/fsr-portal/files # Please change this to the relevant share
#    mountPath:
#      path: /opt/data/files
#  temp:
#    server: 192.168.1.11 # Please change this to your NFS server
#    serverPath:
#      path: /var/www/nfsshare/sandbox/fsr-portal/temp # Please change this to the relevant share
#    mountPath:
#      path: /opt/data/temp

configMaps:
  enabled: false
configMap: []
#    laravel:
#        filepath:
#            path: config/laravel/.env
#        mountPath:
#            path: /var/www/html/project-app/.env
#        fileName:
#            name: .env
#        permission: "0777"
#        readOnly: false

nodeSelector: {}

tolerations: []

affinity: {}
